openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0

paths:
  /auth/google:
    post:
      tags:
        - auth
      summary: "Google 로그인을 요청합니다."
      operationId: "googleLogin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenDto"
      responses:
        "200":
          description: JWT 토큰 발급 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto"

  /auth/refresh:
    post:
      tags:
        - auth
      summary: "서버에서 발급한 refresh token을 통해 accessToken을 다시 받아옵니다."
      operationId: "authRefresh"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  description: "리프레시 토큰"
              required:
                - refreshToken
      responses:
        "200":
          description: JWT 토큰 발급 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto"

  /user/me:
    get:
      tags:
        - user
      summary: "내 유저 정보를 가져옵니다."
      operationId: "getUserInfo"
      responses:
        "200":
          description: "유저 정보 조회 성공"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfoDto"

  /user:
    patch:
      tags:
        - user
      summary: "유저 정보를 업데이트합니다."
      operationId: "updateUserInfo"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserInfoDto"
      responses:
        "200":
          description: "업데이트 성공"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfoDto"

components:
  schemas:
    TokenDto:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - accessToken

    BaseUserStudyLanguage:
      type: object
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          nullable: true
        uid:
          readOnly: true
          type: string
          format: uuid
        language:
          type: string
          enum: [EN, KO]
          description: "학습 언어"
        level:
          type: string
          enum: [EASY, NORMAL, HARD]
          description: "학습 레벨"
        purpose:
          type: string
          description: "학습 목적"
      required:
        - id
        - uid

    BaseUserInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "유저 ID"
        email:
          type: string
          description: "유저 이메일"
        username:
          type: string
          description: "유저 이름"
        birthday:
          type: string
          format: date
          description: "유저 생년월일 (yyyy-MM-dd)"
        gender:
          type: string
          description: "유저 성별"
          enum: [MALE, FEMALE, OTHER]
      required:
        - id
        - email
        - username
        - birthday
        - gender

    UserInfoDto:
      allOf:
        - $ref: "#/components/schemas/BaseUserInfo"
        - type: object
          properties:
            studyLanguages:
              type: array
              items:
                $ref: "#/components/schemas/BaseUserStudyLanguage"
          required:
            - studyLanguages

    UpdateUserInfoDto:
      allOf:
        - $ref: "#/components/schemas/BaseUserInfo"
        - type: object
          properties:
            id:
              readOnly: true
            studyLanguages:
              type: array
              items:
                $ref: "#/components/schemas/BaseUserStudyLanguage"

          required:
            - username
            - birthday
            - gender
            - studyLanguages
