openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0
paths:
  /hello:
    get:
      tags:
        - hello
      summary: "Hello 엔드포인트"
      operationId: "getHello"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /hello/json:
    get:
      tags:
        - hello
      summary: "Hello JSON 엔드포인트"
      operationId: "getHelloJson"
      parameters:
        - $ref: "#/components/parameters/TextQueryParam"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/YourTextDto"
  /auth/google:
    post:
      tags:
        - auth
      summary: "Google 로그인 엔드포인트"
      operationId: "googleLogin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenDto" # 요청 DTO
      responses:
        "200":
          description: JWT 토큰 발급 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto" # 응답 DTO
  /user/me:
    get:
      tags:
        - user
      summary: "내 유저 정보 가져오기"
      operationId: "getUserInfo"
      responses:
        "200":
          description: "유저 정보 조회 성공"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfoDto"

components:
  parameters:
    TextQueryParam:
      name: text
      in: query
      description: "텍스트 입력"
      required: true
      schema:
        type: string
  schemas:
    YourTextDto:
      type: object
      properties:
        yourText:
          type: string
    TokenDto:
      type: object
      properties:
        accessToken:
          type: string
          description: "Google OAuth Token"
      required:
        - accessToken
    UserInfoDto:
      type: object
      properties:
        id:
          type: string
          description: "유저 ID"
        email:
          type: string
          description: "유저 이메일"
        startAtMillis:
          type: integer
          description: "유저 시작 시간 (밀리초 단위)"
        endAtMillis:
          type: integer
          description: "유저 종료 시간 (밀리초 단위)"
      required:
        - id
        - email
        - startAtMillis
        - endAtMillis
