openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0
paths:
  /auth/google:
    post:
      tags:
        - auth
      summary: "Google 로그인 엔드포인트"
      operationId: "googleLogin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenDto" # 요청 DTO
      responses:
        "200":
          description: JWT 토큰 발급 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto" # 응답 DTO
  /auth/refresh:
    post:
      tags:
        - auth
      summary: "서버에서 발급한 refresh token을 통해 accessToken을 다시 받아옵니다. "
      operationId: "authRefresh"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  description: "리프레시 토큰"
              required:
                - refreshToken
      responses:
        "200":
          description: JWT 토큰 발급 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto" # 응답 DTO
  /user/me:
    get:
      tags:
        - user
      summary: "내 유저 정보 가져오기"
      operationId: "getUserInfo"
      responses:
        "200":
          description: "유저 정보 조회 성공"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfoDto"

components:
  schemas:
    TokenDto:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
      required:
        - accessToken
    UserInfoDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: "유저 ID"
        email:
          type: string
          description: "유저 이메일"
      required:
        - id
