openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: "Hello 엔드포인트"
      operationId: "getHello"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
